### ISSUE TITLE
Pixel 7 no unlock 48khz

### ISSUE THREAD

**Issue by PrincessOfHell** [Magisk-Modules-Alt-Repo/usb-samplerate-unlocker#5]
First, I want to say that I am an audio enthusiast. T
![Screenshot_20231017-221908](https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker/assets/1158444/84ddcf82-0b8b-4f91-a629-cc46572da1eb)
his module cannot unlock the 48khz limit with a pixel 7 pro and Android 14. My DAC is an E1DA.  It supports 384kHz and DSD 256. Is there a possible solution?  I can do the tests if you patch the module.

**Comment by yzyhk904** [comment]
Tensor devices have two audio mixers, i.e., "deep_buffer" (for non-hires. formats) and "hifi_playback" (for hires. formats). "deep_buffer" is default and usually used at 48kHz & 24bit depth for 44.1 & 48 kHz audio tracks, but "hifi_playback" shall be activated (at 96kHz (unlocked stock) or 192kHz if my unlocker is used) when hirs. audio track playing.

The USB offload driver of Tensor devices can output only 48kHz and 96kHz as stock, and my unlocker changes it to 44.1kHz, 48kHz, 96kHz and 192kHz unlike other devices, e.g., MTK and Qcomm devices.

I recommend trying my another module [Hifi Maximizer](https://github.com/yzyhk904/hifi-maximizer-mod) once instead of this module. It changes all the work you need perhaps and you could hear 192kHz & 32bit depth sound easily for non-hires. and hires. tracks.

**Comment by PrincessOfHell** [comment]
okay.  hi fi maximizer mod works with my pixel 7 pro.  qobuz plays at 192khz/24 bit.  thank you.
