### ISSUE TITLE
Pixel 8 Pro No Sound

### ISSUE THREAD

**Issue by liberty-strongly660** [Magisk-Modules-Alt-Repo/usb-samplerate-unlocker#9]
I had been using this module on Pixel 7 Pro and Pixel 6 Pro on A 13 stock rom without any issues. I was elated to see that the scope of this module was extended to Pixel 8 Pro, however once I flashed on my current Pixel 8 Pro, the flash went without any issues but there was no sound coming out of the phone speaker after reboot. Sound was back after removing the module. Please don't get me wrong when I say this, but did you make this module compatible with A14? I mean is it possible that you extended the module to Pixel 8 devices but didnt extend the same to A14 (I say this cos in your change log you still mention of A13). Pixel 8 was released with A14 stock.

Regards and thanks

**Comment by yzyhk904** [comment]
I've heard this module was running well on Pixel 6's and Pixel 7's with A14. And someone sent me a patch for Pixel 8 PRO to fix its board name ("gs*" to "zuma"), so I've thought the latest released zip of this module could run well on Pixel 8's with A14.

Any way, Pixel 8's don't need this module because they can output at 192kHz for replaying Hires. tracks natively unlike Pixel 6's and 7's. (This module's merit for Pixel 8's is only to reduce their jitter for better audio quality)

I have no idea now for your issue because I don't have any Pixel 8's.
